'use statics';

export default {
  BEGIN_FETCHING_ME: 'BEGIN_FETCHING_ME',
  SUCCESS_FETCHING_ME: 'SUCCESS_FETCHING_ME',
  ERROR_FETCHING_ME: 'ERROR_FETCHING_ME',

  FETCH_LIKES: 'FETCH_LIKES',
  FETCH_TRACKS: 'FETCH_TRACKS',
  FETCH_USER: 'FETCH USER'
};