'use statics';

export default {
  BEGIN_GET_ME: 'BEGIN_GET_ME',
  SUCCESS_GET_ME: 'SUCCESS_GET_ME',
  ERROR_GET_ME: 'ERROR_GET_ME',

  BEGIN_GET_LIKES: 'BEGIN_GET_LIKES',
  SUCCESS_GET_LIKES: 'SUCCESS_GET_LIKES',
  ERROR_GET_LIKES: 'ERROR_GET_LIKES'
};